  function [data, auxData, metaData, txtData, weights] = mydata_Danio_rerio

%% set metadata
metaData.phylum     = 'Chordata'; 
metaData.class      = 'Actinopterygii'; 
metaData.order      = 'Cypriniformes'; 
metaData.family     = 'Danionidae';
metaData.species    = 'Danio_rerio'; 
metaData.species_en = 'Zebra fish'; 

metaData.ecoCode.climate = {'Am'};
metaData.ecoCode.ecozone = {'TPi'};
metaData.ecoCode.habitat = {'0iFp', '0iFm'};
metaData.ecoCode.embryo  = {'Fh'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biCi'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(25); % K, body temp
metaData.data_0     = {'ab'; 'aj'; 'ap'; 'am'; 'L0'; 'Lb'; 'Lj'; 'Lp'; 'Li'; 'Wd0'; 'Wwi'; 'Ri'; 'GSI'}; 
metaData.data_1     = {'t-Le'; 't-Wwe'; 't-Wde'; 't-MCe'; 't-MNe'; 't-L_fT'; 't-Ww_f'; 't-N'; 't-S'; 'L-Ww'}; 

metaData.COMPLETE = 4.6; % using criteria of LikaKear2011

metaData.author   = {'Starrlight Augustine'};        
metaData.date_subm = [2011 05 02];                           
metaData.email    = {'sta@akvaplan.niva.no'};                 
metaData.address  = {'Akvaplan-niva AS, Fram Centre, P.O. Box 6606 Langnes, 9296 Tromso, Norway'}; 

metaData.author_mod_1   = {'Starrlight Augustine'};        
metaData.date_mod_1 = [2018 08 08];                           
metaData.email_mod_1    = {'starrlight.augustine@akvaplan.niva.no'};                 
metaData.address_mod_1  = {'Akvaplan-niva AS, Fram Centre, P.O. Box 6606 Langnes, 9296 Tromso, Norway'}; 

metaData.curator     = {'Bas Kooijman'};
metaData.email_cur   = {'bas.kooijman@vu.nl'}; 
metaData.date_acc    = [2018 08 09]; 

%% set data
% zero-variate data
data.ab = 5;      units.ab = 'd';    label.ab = 'age at birth';           bibkey.ab = 'BestAdat2010'; 
  temp.ab = C2K(25);  units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.aj = 22;     units.aj = 'd';    label.aj = 'age at metam';           bibkey.aj = 'BestAdat2010'; 
  temp.aj = C2K(25); units.temp.aj = 'K'; label.temp.aj = 'temperature';
  comment.aj = 'length at 1 cm';
data.ap = 75;     units.ap = 'd';    label.ap = 'age at puberty';         bibkey.ap = 'EatoFarl1974a'; 
  temp.ap = C2K(25.5);  units.temp.ap = 'K'; label.temp.ap = 'temperature';
  comment.ap = '(74 - 75 day of development)';
data.am = 4.5 * 365; units.am = 'd'; label.am = 'life span';              bibkey.am = 'GerhKauf2002';   
  temp.am = C2K(26); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lb = 4e-1;   units.Lb = 'cm';   label.Lb = 'total length at birth';  bibkey.Lb = 'Schi2002';
  comment.Lb = 'Swim bladder inflates, active feeding, pronephric tubules';
data.Lj = 1;   units.Lj = 'cm';   label.Lj = 'total length at metam';  bibkey.Lj = 'Schi2002';
  comment.Lj = 'Adult fin and pigmentation pattern';
data.Lp = 2.6*1.25; units.Lp = 'cm'; label.Lp = 'total length at puberty';bibkey.Lp = 'EatoFarl1974a';
  comment.Lp = 'Female are between 2.4 - 2.6 cm SL in the study at first egg laying';
data.Li = 5;      units.Li = 'cm';   label.Li = 'ultimate total length';  bibkey.Li = {'SpenGerl2008','Schi2002'}; 
  comment.Li = 'also Lawr pers. comm';

data.Wwi = 1;      units.Wwi = 'g';    label.Wwi = 'ultimate wet weight';    bibkey.Wwi = 'Augu2009';

data.Ri = 240;    units.Ri = '#/d';  label.Ri = 'max reproduction';       bibkey.Ri = {'EatoFarl1974b'}; 
  temp.Ri = C2K(26);  units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  
data.GSI = 0.15;  units.GSI = 'g/g';   label.GSI = 'Gonado Somatic Index';  bibkey.GSI = {'ForbPres2010'}; 
  temp.GSI = C2K(26); units.temp.GSI = 'K'; label.temp.GSI = 'temperature';
  init.GSI = 3; units.init.GSI = 'd'; label.init.GSI = 'simulation time for GSI';
  comment.GSI = 'values range from 0.1 - 0.15 and grow bigger with food regime';

  
% uni-variate data
% time-wet weight weight data at T = 273 + 25 K
tLWWY = [ ... % age d, length mm, wet W mg, dry W mg, yolk mm^3
 4	3.9  .331  .061 .065;
 5	4.0  .338  .055 .055;
10	4.2  .397  .064 .030;
12	4.4  .440  .073 0;
14	4.6  .448  .075 0;
25	6.4  1.38  .180 0;
28	6.9  2.16  .350 0;
31	8.2  3.69  .610 0];
tLWWY(:,2) = tLWWY(:,2)/ 10; % convert mm to cm
tLWWY(:,[3 4 5]) = tLWWY(:,[3 4 5])/ 1000; % convert mg to g, mm^3 to cm^3
%
data.tL_BagaPels2001 = tLWWY(:, [1 2]);
units.tL_BagaPels2001 = {'d', 'cm'};  label.tL_BagaPels2001 = {'time since fertilizatixon', 'total length'};
  temp.tL_BagaPels2001 = C2K(25);  units.temp.tL_BagaPels2001 = 'K'; label.temp.tL_BagaPels2001 = 'temperature';
bibkey.tL_BagaPels2001 = {'BagaPels2001'};
%
data.tWw_BagaPels2001 = tLWWY(:, [1 3]);
units.tWw_BagaPels2001 = {'d', 'g'};  label.tWw_BagaPels2001 = {'time since fertilization', 'wet weight'};
bibkey.tWw_BagaPels2001 = {'BagaPels2001'};

% BestAdat2010 T = 25 C, rotifers from day 5 till 9, then transition to
% regular feeding from 9 till 12 was originally given in personnal
% communication with C. Lawrence
% I digitalized all the points which in fact
% correspond to 2 different strains (AB and nacre)
% time-length
data.tL_BestAdat2010 = [... age (dpf), total length (cm)
5.00741992	0.30707071;
5.01034883	0.42828283;
5.97532950	0.36363636;
5.97698922	0.43232323;
6.99107806	0.40000000;
6.99215200	0.44444444;
7.96045210	0.51717172;
8.00731478	0.45656566;
8.97571251	0.53333333;
9.94401261	0.60606061;
10.95819908	0.57777778;
10.95946828	0.63030303;
11.97404528	0.61818182;
11.97648604	0.71919192;
16.03869925	0.83232323;
16.03996845	0.88484848;
23.10393150	1.22424242;
23.10481018	1.26060606;
30.17170214	1.72121212;
90 3.19;
90 3.41];
units.tL_BestAdat2010 = {'d', 'cm'}; label.tL_BestAdat2010 = {'time since fertilization', 'total length'}; 
  temp.tL_BestAdat2010 = C2K(25); units.temp.tL_BestAdat2010 = 'K'; label.temp.tL_BestAdat2010 = 'temperature';
bibkey.tL_BestAdat2010 = {'BestAdat2010'};

% time-length from study LawrEber2008, but the actual curves were given in pers.
% communication with C. Lawrence T = 28.5 C and there is about 50 %
% difference in food given between the high and the low food condition
data.tL_LawrEber2002_high = [... % day, cm T = 28 + 273 K Total Length
3.55e+00	3.89e-01 
1.07e+01	5.66e-01
1.09e+01	5.05e-01
1.09e+01	5.39e-01
1.80e+01	9.21e-01
1.82e+01	7.91e-01
1.82e+01	8.87e-01
2.55e+01	1.41e+00
2.55e+01	1.46e+00
2.56e+01	1.23e+00
2.56e+01	1.30e+00
3.28e+01	1.56e+00
3.28e+01	1.67e+00
3.28e+01	1.78e+00
3.28e+01	1.92e+00
4.01e+01	2.30e+00
4.01e+01	1.91e+00
4.01e+01	2.05e+00
4.02e+01	2.22e+00
4.74e+01	2.42e+00
4.74e+01	2.63e+00
4.75e+01	2.27e+00
5.46e+01	2.42e+00
5.47e+01	2.80e+00
5.47e+01	2.50e+00
6.19e+01	3.13e+00
6.20e+01	2.72e+00
6.20e+01	3.04e+00
6.20e+01	2.42e+00
6.92e+01	2.91e+00
6.92e+01	3.15e+00
6.92e+01	3.24e+00
6.93e+01	2.74e+00
7.65e+01	2.95e+00
7.65e+01	3.23e+00
7.66e+01	3.34e+00
7.66e+01	2.82e+00
8.38e+01	3.18e+00
8.38e+01	3.24e+00
8.38e+01	3.31e+00
8.38e+01	3.36e+00];
units.tL_LawrEber2002_high = {'d', 'cm'}; label.tL_LawrEber2002_high = {'time since birth', 'total length'}; 
  temp.tL_LawrEber2002_high = C2K(28.5); units.temp.tL_LawrEber2002_high = 'K'; label.temp.tL_LawrEber2002_high = 'temperature';
bibkey.tL_LawrEber2002_high = {'LawrEber2008'};
%
data.tL_LawrEber2002_low = [... % day, cm T = 28 + 273 K Total Length
3.55e+00	3.62e-01
1.09e+01	4.50e-01
1.81e+01	6.55e-01
2.55e+01	8.73e-01
2.55e+01	9.69e-01
3.28e+01	1.02e+00
3.28e+01	1.14e+00
3.28e+01	1.18e+00
3.99e+01	1.36e+00
4.74e+01	1.61e+00
4.74e+01	1.51e+00
4.74e+01	1.54e+00
4.75e+01	1.73e+00
5.47e+01	1.71e+00
5.47e+01	1.81e+00
6.19e+01	1.82e+00
6.20e+01	1.60e+00
6.20e+01	1.97e+00
6.92e+01	1.82e+00
6.92e+01	1.96e+00
6.93e+01	2.09e+00
6.93e+01	2.18e+00
7.66e+01	2.03e+00
7.66e+01	2.10e+00
7.66e+01	2.18e+00
8.37e+01	2.13e+00
8.37e+01	2.16e+00
8.37e+01	2.24e+00
8.38e+01	2.28e+00];
units.tL_LawrEber2002_low = {'d', 'cm'}; label.tL_LawrEber2002_low = {'time since birth', 'total length'}; 
  temp.tL_LawrEber2002_low = C2K(28.5); units.temp.tL_LawrEber2002_low = 'K'; label.temp.tL_LawrEber2002_low = 'temperature';
bibkey.tL_LawrEber2002_low = {'LawrEber2008'};

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% Auto add titles to univariate data
title = struct();
datanames = fieldnames(data);
for i=1:numel(datanames)
    datum = datanames{i};
    % Skip zero-variate data
    if isscalar(data.(datum))
        continue
    end
    if ~isfield(title, datum)
        dataTitle = [strjoin(label.(datum), ' vs ') ', ' datum];
        if isfield(bibkey, datum)
            dataTitle = [dataTitle ', ' bibkey.(datum){:}];
        end
        title.(datum) = dataTitle;
    end
end

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.init = init;

txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;
txtData.title = title;

%% Group plots
set1 = {'tL_LawrEber2002_high','tL_LawrEber2002_low'}; subtitle1 = {'LawrEber2002 data at high, low food'};
metaData.grp.sets = {set1};
metaData.grp.subtitle = {subtitle1};

% metaData.grp.sets = {set3,set5};
% metaData.grp.subtitle = {subtitle3,subtitle5};


%% Discussion points
D1 = 'version 2018 08 08: KimBall95 and Augu2011 no longer included';
D2 = 'version 2018 08 08: studies by GomeConc2010, SchaRyan2006, BarrFern2010, BarrBurg1999, are not longer included. Previous version included them but gave them zero weight because growth deviates from what is assumed to be the normal patterns of growth at constant food (see EatoFarly1974,LawrEber2008,  Schi2002, BestAdat2010 and discussion in AuguGagn2011)';     
D3 = 'version 2018 08 08: it is no longer possible to implement different Arrhennius temperatures for embryo and adult';
D4 = 'version 2018 08 08: Egg respiration data from BangGron2004 is not longer included, the data show that the respiration stops quite early on while development and growth is very fast. We think this is an artefact. You can find back the data in the previous version.';
D5 = 'version 2018 08 08: inclusion of juvenile growth and adult reproduction data from BeauGous2015.';
D6 = 'version 2018 08 08: Buffer handling rules from AuguGagn2012 are used for modelling starvation response. We  estimate at adult females have  200 and 800 J in the reproduction buffer at the start of the trials. This is in line with finding from AuguGang2012'; 
D7 = 'version 2018 08 08: standard length is 80% of the total length:';
metaData.discussion = struct('D1',D1,'D2',D2,'D3',D3,'D4',D4,'D5',D5, 'D6', D6, 'D7', D7);
                                 
%% Links
metaData.links.id_CoL = '3443J'; % Cat of Life
metaData.links.id_ITIS = '163668'; % ITIS
metaData.links.id_EoL = '204011'; % Ency of Life
metaData.links.id_Wiki = 'Danio_rerio'; % Wikipedia
metaData.links.id_ADW = 'Danio_rerio'; % ADW
metaData.links.id_Taxo = '172875'; % Taxonomicon
metaData.links.id_WoRMS = '1026595'; % WoRMS
metaData.links.id_fishbase = 'Danio-rerio'; % fishbase

%% References
bibkey = 'Wiki'; type = 'Misc'; bib = ...
'howpublished = {\url{https://en.wikipedia.org/wiki/Zebrafish}}';  
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{../../../bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'AuguGagn2011'; type = 'Article'; bib = [ ...  
'author = {S. Augustine and B. Gagnaire and C. Adam and S. A. L. M. Kooijman}, ' ...
'year = {2011}, ' ...
'title = {Developmental energetics of zebrafish, \emph{Danio rerio}}, ' ... 
'howpublished = {\url{https://www.zotero.org/groups/500643/deb_library/items/WFHER6ED/item-details}}, ' ...
'journal = {Comp. Physiol. Biochem. A}, ' ...
'volume = {159}, '...
'pages = {275-283}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SpenGerl2008'; type = 'Article'; bib = [ ...  
'author = {Spence, R. and Gerlach, G. and Lawrence, C. and Smith, C.}, ' ...
'year = {2008}, ' ...
'title = {The behaviour and ecology of the zebrafish, \emph{Danio rerio}}, ' ... 
'journal = {Biol. Rev.}, ' ...
'volume = {83}, '...
'pages = {13-34}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'LawrEber2008'; type = 'Article'; bib = [ ...  
'author = {Lawrence, C. and Ebersole, J. P. and Kesseli, R. V.}, ' ...
'year = {2008}, ' ...
'title = {Rapid growth and out-crossing promote female development in zebrafish (\emph{Danio rerio})}, ' ... 
'journal = {Environ. Biol. Fish.}, ' ...
'volume = {81}, '...
'pages = {239-246}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BagaPels2001'; type = 'Article'; bib = [ ...    
'author = {Bagatto, B. and Pelster, B. and Burggren, W. W.}, ' ...
'year  = {2001}, ' ...
'title = {Growth and metabolism of larval zebrafish: effects of swim training}, ' ...  
'journal = {Journal of Experimental Biology}, ' ...
'volume = {204}, ' ...
'pages = {4335-4343}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BangGron2004'; type = 'Article'; bib = [ ...    
'author = {A. Bang and P. Gr{\o}nj{\ae}r and H. Malte}, ' ...
'year  = {2004}, ' ...
'title = {Individual variation in the rate of oxygen consumption by zebrafish embryos}, ' ...  
'journal = {Journal of Fish Biology}, ' ...
'volume = {64}, ' ...
'pages = {1285-1296}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BarrFern2010'; type = 'Article'; bib = [ ...    
'author = {Barrionuevo, W. R. and Fernandes, M. N. and Rocha, O.}, ' ...
'year  = {2010}, ' ...
'title = {Aerobic and anaerobic metabolism for the zebrafish, \emph{Danio rerio}, reared under normoxic and hypoxic conditions and exposed to acute hypoxia during development}, ' ...  
'journal = {Brazilian Journal of Biology}, ' ...
'volume = {70}, ' ...
'pages = {425-434}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BarrBurg1999'; type = 'Article'; bib = [ ...    
'author = {Barrionuevo, W. R. and Burggren, W. W.}, ' ...
'year  = {1991}, ' ...
'title = {O2 consumption and heart rate in developing zebrafish (\emph{Danio rerio}): Influence of temperature and ambient O2.}, ' ...  
'journal = {American Journal of Physiology - Regulatory Integrative and Comparative Physiology}, ' ...
'volume = {276}, ' ...
'pages = {505-513}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BestAdat2010'; type = 'Article'; bib = [ ...    
'author = {Best, J. and Adatto, I. and Cockington, J. and James, A. and Lawrence, C.}, ' ...
'year  = {2010}, ' ...
'title = {A novel method for rearing first feeding larval zebrafish: polyculture with {T}ype {L} saltwater rotifers (\emph{Brachionus plicatilis}).}, ' ...  
'journal = {Zebrafish}, ' ...
'volume = {352 7(3)}, ' ...
'pages = {89-295}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'EatoFarl1974a'; type = 'Article'; bib = [ ...    
'author = {Eaton, R. C. and Farley, R. D.}, ' ...
'year  = {1974}, ' ...
'title = {Growth and the reduction of depensation of zebrafish, \emph{Brachydanio rerio}, reared in the laboratory}, ' ...  
'journal = {Copeia}, ' ...
'volume = {1}, ' ...
'pages = {204-209}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'EatoFarl1974b'; type = 'Article'; bib = [ ...    
'author = {Eaton, R. C. and Farley, R. D.}, ' ...
'year  = {1974}, ' ...
'title = {Spawning cycle and egg production of zebrafish, \emph{Brachydanio rerio} in the laboratory}, ' ...  
'journal = {Copeia}, ' ...
'volume = {1}, ' ...
'pages = {195-204}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'GerhKauf2002'; type = 'Article'; bib = [ ...    
'author = {Gerhard, G. S. and Kauffman, E. J. and Wang, X. and Stewart, R. and Moore, J. L. and Kasales, C. J. and Demidenko, E. and Cheng, K. C.}, ' ...
'year  = {2002}, ' ...
'title = {Life spans and senescent phenotypes in two strains of Zebrafish (\emph{Danio rerio})}, ' ...  
'journal = {Experimental Gerontology}, ' ...
'volume = {37(8-9)}, ' ...
'pages = {1055-1068}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'GomeConc2010'; type = 'Article'; bib = [ ...    
'author = {Gomez-Requeni, P. and Concei{\c}{\a~}o, L. E. C. and Olderbakk Jordal, A. E. and R{\o}nnestad, I.}, ' ...
'year  = {2010}, ' ...
'title = {A reference growth curve for nutritional experiments in zebrafish (\emph{Danio rerio}) and changes in whole body proteome during development}, ' ...  
'journal = {Fish Physiology and Biochemistry}, ' ...
'doi = {10.1007/s10695-010-9400-0}, ' ...
'volume = {36}, ' ...
'pages = {1199-1215}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'KimmBall1995'; type = 'Article'; bib = [ ...    
'author = {Kimmel, C. B. and Ballard, W. W. and Kimmel, S. R. and Ullmann, B. and Schilling, T. F.}, ' ...
'year  = {1995}, ' ...
'title = {Stages of embryonic development of the zebrafish}, ' ...  
'journal = {Developmental Dynamics}, ' ...
'volume = {203}, ' ...
'pages = {253-310}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'LawrEber2008'; type = 'Article'; bib = [ ...    
'author = {Lawrence, C. and Ebersole, J. P. and Kesseli, R. V.}, ' ...
'year  = {2008}, ' ...
'title = {Rapid growth and out-crossing promote female development in zebrafish (\emph{Danio rerio})}, ' ...  
'journal = {Environmental Biology of Fishes}, ' ...
'volume = {81}, ' ...
'pages = {239-246}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SchaRyan2006'; type = 'Article'; bib = [ ...    
'author = {J. Schaefer and A. Ryan}, ' ...
'year  = {2006}, ' ...
'title = {Developmental plasticity in the thermal tolerance of zebrafish \emph{Danio rerio}}, ' ...  
'journal = {Journal of Fish Biology}, ' ...
'volume = {69}, ' ...
'pages = {722-734}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Schi2002'; type = 'Incollection'; bib = [ ...    
'author = {Schilling, T. F.}, ' ...
'year  = {2002}, ' ...
'booktitle = {Zebrafish: a practical guide}, ' ...
'editor = {Nusslein-Volhard, C. and Dahm, R.}, ' ...
'title = {The morphology of larval and adult zebrafish}, ' ...  
'publisher = {Oxford University Press Inc.}, ' ...
'address = {New York}, ' ...
'pages = {59-83}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Augu2009'; type = 'Misc'; bib = [ ...
'year = {2009}, ' ...
'author = {S. Augustine}, ' ...
'note = {unpublished 2009, f = 1}'];  
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'ForbPres2010'; type = 'Article'; bib = [ ...
'author = {Forbes, E. L. and Preston, C. D. and Lokman, P. M.}, ' ...
'year  = {2010}, ' ...
'title = {Zebrafish (\emph{Danio rerio}) and the egg size versus egg number trade off: effects of ration size on fecundity are not mediated by orthologues of the {F}ec gene}, ' ...  
'journal = {Reprod. Fert. Dev.}, ' ...
'volume = {22}, ' ...
'pages = {1015-1021}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BeauGous2015'; type = 'Article'; bib = [ ...
'doi = {10.1371/journal.pone.0125841}, ' ...
'author = {Beaudouin, R. and Goussen, B. and Piccini, B. and Augustine, S. and Devillers, J. and Brion, F. and P\`{e}ry, A. R. R.}, ' ...
'year  = {2015}, ' ...
'title = {An Individual-Based Model of Zebrafish Population Dynamics Accounting for Energy Dynamics}, ' ...  
'journal = {PloS one}, ' ...
'volume = {10}, ' ...
'number = {5}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'DrewRodn2008'; type = 'Article'; bib = [ ...  
'author = {Drew, Robert E. and Rodnick, Kenneth J. and Settles, Matthew and Wacyk, Jurij and Churchill, Erin and Powell, Madison S. and Hardy, Ronald W. and Murdoch, Gordon K. and Hill, Rodney A. and Robison, Barrie D.}, ' ...
'year = {2008}, ' ...
'title = {Effect of starvation on transcriptomes of brain and liver in adult female zebrafish (\emph{Danio rerio})}, ' ... 
'journal = {Physiological Genomics}, ' ...
'volume = {35}, '...
'pages = {283-295}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'GeffSimo2013'; type = 'Article'; bib = [ ...  
'author = {Benjamin Geffroy and Olivier Simon}, ' ...
'year = {2013}, ' ...
'title = {Effects of a \emph{Spirulina platensis}-based diet on zebrafish female reproductive performance and larval survival rate}, ' ... 
'journal = {Cybium}, ' ...
'volume = {37}, '...
'pages = {31-38}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Baye2005'; type = 'Misc'; bib = [ ...
'author = {Bayer, A.G.}, ' ... 
'year = {2005}, ' ...
'note = {Control data from OECD tests, report number M-247419-01-1 F0 generation rep. 1 day 0}}, ' ...
'howpublished = {\url{https://cropscience-transparency.bayer.com/en/Study-Results}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BarrFern2010'; type = 'Article'; bib = [ ...  
'author = {Barrionuevo, W.R. and Fernandes, M.N. anf Rocha, O.}, ' ...
'year = {2010}, ' ...
'title = {Aerobic and anaerobic metabolism for the zebrafish, \textit{Danio rerio}, reared under normoxic and hypoxic conditions and exposed to acute hypoxia during development}, ' ... 
'journal = {Braz. J. Biol.}, ' ...
'volume = {70}, '...
'pages = {425-434}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'LiciFron2024'; type = 'Article'; bib = [ ...  
'author = {Licitra, Rosatio and Fronte, Baldassare and Verri, Tiziano and Marchese, Maria and Sangiacomo, Chiara and Santorelli, Filippo Maria}, ' ...
'year = {2024}, ' ...
'title = {Zebrafish feed intake: a systematic review for standardizing feeding managment in laboratory conditions}, ' ... 
'journal = {Biology}, ' ...
'volume = {13}, '...
'pages = {209}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BarrBurg1999'; type = 'Article'; bib = [ ...  
'author = {Barrionuevo, W.R. and Burggren W. W.}, ' ...
'year = {1999}, ' ...
'title = {O2 consumption and heart rate in developing zebrafish, (\textit{Danio rerio}): influence of temperature and ambient O2}, ' ... 
'journal = {Am. J. Physiol.}, ' ...
'volume = {276}, '...
'pages = {505-513}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
