function [data, auxData, metaData, txtData, weights] = mydata_Danio_rerio

%% set metadata
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Cypriniformes';
metaData.family     = 'Danionidae';
metaData.species    = 'Danio_rerio';
metaData.species_en = 'Zebra fish';

metaData.ecoCode.climate = {'Am'};
metaData.ecoCode.ecozone = {'TPi'};
metaData.ecoCode.habitat = {'0iFp', '0iFm'};
metaData.ecoCode.embryo  = {'Fh'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biCi'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(25); % K, body temp
metaData.data_0     = {'ab'; 'aj'; 'ap'; 'am'; 'L0'; 'Lb'; 'Lj'; 'Lp'; 'Li'; 'Wd0'; 'Wwi'; 'Ri'; 'GSI'};
metaData.data_1     = {'t-Le'; 't-Wwe'; 't-Wde'; 't-MCe'; 't-MNe'; 't-L_fT'; 't-Ww_f'; 't-N'; 't-S'; 'L-Ww'};

metaData.COMPLETE = 4.6; % using criteria of LikaKear2011

metaData.author   = {'Starrlight Augustine'};
metaData.date_subm = [2011 05 02];
metaData.email    = {'sta@akvaplan.niva.no'};
metaData.address  = {'Akvaplan-niva AS, Fram Centre, P.O. Box 6606 Langnes, 9296 Tromso, Norway'};

metaData.author_mod_1   = {'Starrlight Augustine'};
metaData.date_mod_1 = [2018 08 08];
metaData.email_mod_1    = {'starrlight.augustine@akvaplan.niva.no'};
metaData.address_mod_1  = {'Akvaplan-niva AS, Fram Centre, P.O. Box 6606 Langnes, 9296 Tromso, Norway'};

metaData.curator     = {'Bas Kooijman'};
metaData.email_cur   = {'bas.kooijman@vu.nl'};
metaData.date_acc    = [2018 08 09];

%% load externalized calibration data
repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, 'data_pipeline'));

%% set data
% zero-variate data
zeroVariateSpecs = { ...
    'ab', ...   % age at birth, BestAdat2010
    'aj', ...   % age at metam, BestAdat2010
    'ap', ...   % age at puberty, EatoFarl1974a
    'am', ...   % life span, GerhKauf2002
    'L0', ...   % egg diameter, ForbPres2010
    'Lb', ...   % total length at birth, Schi2002
    'Lj', ...   % total length at metam, Schi2002
    'Lp', ...   % standard length at puberty, EatoFarl1974a
    'Li', ...   % ultimate total length, SpenGerl2008 and Schi2002
    'Wd0', ...  % egg dry weight, Augu2011
    'Wwi', ...  % ultimate wet weight, Augu2011
    'Ri', ...   % max reproduction, EatoFarl1974b
    'GSI' ...   % Gonado Somatic Index, ForbPres2010
    };

% tim-length, larval growth curve T = 28.5 + 273 K, total length
schi2002Specs = { ...
    'tL_Schi2002' ... % time-length data, Schi2002
    };

% time-length at T = 25.5 + 273 K, standard length
eatoFarl1974Specs = { ...
    'tL_EatoFarl1974' ... % time-length data, EatoFarl1974b
    };

% time-length, wet-weight, and dry-weight data at T = 25 C
bagaPels2001Specs = { ...
    'tL_BagaPels2001', ... % age vs standard length, BagaPels2001
    'tWw_BagaPels2001', ... % age vs wet weight, BagaPels2001
    'tWd_BagaPels2001' ... % age vs dry weight, BagaPels2001
    };

% BestAdat2010 T = 25 C, larval time-length data digitized from the study
bestAdat2010Specs = { ...
    'tL_BestAdat2010' ... % larval time-length data, BestAdat2010
    };

% time-length from LawrEber2008 at 28.5 C under high and low food conditions
lawrEber2008Specs = { ...
    'tL_LawrEber2008_high', ... % high-food growth curve, LawrEber2008
    'tL_LawrEber2008_low' ... % low-food growth curve, LawrEber2008
    };

% BeauGous2015 fasting treatments and reproduction summaries
beauGous2015Specs = { ...
    'tLf1_BeauGous2015', ... % no fasting length trajectory, BeauGous2015
    'tLf2_BeauGous2015', ... % fasting every 3 days length trajectory, BeauGous2015
    'tLf3_BeauGous2015', ... % fasting every other day length trajectory, BeauGous2015
    'tL1', ... % juvenile standard-length series from courtesy raw data
    'Wwt', ... % final wet weight summary from courtesy raw data
    'tN' ... % cumulative egg production from courtesy raw data
    };

% Valentine and Kwasek feeding-rate experiment
valKwa2022Specs = { ...
    'tWw_ValKwa2022', ... % age vs wet weight, ValKwa2022
    'tL_ValKwa2022', ... % age vs total length, ValKwa2022
    'tJX_ValKwa2022' ... % age vs feed intake, ValKwa2022
    };

% Yang and Yamamoto growth, body mass, and oxygen-consumption data
yangYama2019Specs = { ...
    'tL_YangYama2019', ... % age vs total length, YangYama2019
    'tWw_YangYama2019', ... % age vs wet weight, YangYama2019
    'tJO_YangYama2019' ... % age vs oxygen consumption, YangYama2019
    };

datasetSpecs = [ ...
    zeroVariateSpecs, ...
    schi2002Specs, ...
    eatoFarl1974Specs, ...
    bagaPels2001Specs, ...
    bestAdat2010Specs, ...
    lawrEber2008Specs, ...
    beauGous2015Specs, ...
    valKwa2022Specs, ...
    yangYama2019Specs];

[data, auxData, externalTxtData] = load_calibration_data(datasetSpecs);

units = externalTxtData.units;
label = externalTxtData.label;
bibkey = externalTxtData.bibkey;
comment = externalTxtData.comment;
temp = auxData.temp;
treat = auxData.treat;
init = auxData.init;

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% Auto add titles to univariate data
title = struct();
datanames = fieldnames(data);
for i=1:numel(datanames)
  datum = datanames{i};
  % Skip zero-variate data
  if isscalar(data.(datum))
    continue
  end
  if ~isfield(title, datum)
    dataTitle = [strjoin(label.(datum), ' vs ') ', ' strrep(datum, '_', '\_');];
    if isfield(bibkey, datum)
      dataTitle = [dataTitle ', ' bibkey.(datum){:}];
    end
    title.(datum) = dataTitle;
  end
end

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.treat = treat;
auxData.init = init;

txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;
txtData.title = title;

%% Group plots
set3 = {'tL_LawrEber2008_high','tL_LawrEber2008_low'}; subtitle3 = {'LawrEber2008 data at high, low food'};
set5 = {'tLf1_BeauGous2015','tLf2_BeauGous2015','tLf3_BeauGous2015'}; subtitle5 = {'no fasting, fasting every 3 d, fasting every other day'};
metaData.grp.sets = {set3,  set5};
metaData.grp.subtitle = {subtitle3,  subtitle5};

%% Discussion points
D1 = 'version 2018 08 08: KimBall95 and Augu2011 no longer included';
D2 = 'version 2018 08 08: studies by GomeConc2010, SchaRyan2006, BarrFern2010, BarrBurg1999, are not longer included. Previous version included them but gave them zero weight because growth deviates from what is assumed to be the normal patterns of growth at constant food (see EatoFarly1974,LawrEber2008,  Schi2002, BestAdat2010 and discussion in AuguGagn2011)';
D3 = 'version 2018 08 08: it is no longer possible to implement different Arrhennius temperatures for embryo and adult';
D4 = 'version 2018 08 08: Egg respiration data from BangGron2004 is not longer included, the data show that the respiration stops quite early on while development and growth is very fast. We think this is an artefact. You can find back the data in the previous version.';
D5 = 'version 2018 08 08: inclusion of juvenile growth and adult reproduction data from BeauGous2015.';
D6 = 'version 2018 08 08: Buffer handling rules from AuguGagn2012 are used for modelling starvation response. We  estimate at adult females have  200 and 800 J in the reproduction buffer at the start of the trials. This is in line with finding from AuguGang2012';
D7 = 'version 2018 08 08: standard length is 80% of the total length:';
metaData.discussion = struct('D1',D1,'D2',D2,'D3',D3,'D4',D4,'D5',D5, 'D6', D6, 'D7', D7);

%% Links
metaData.links.id_CoL = '3443J'; % Cat of Life
metaData.links.id_ITIS = '163668'; % ITIS
metaData.links.id_EoL = '204011'; % Ency of Life
metaData.links.id_Wiki = 'Danio_rerio'; % Wikipedia
metaData.links.id_ADW = 'Danio_rerio'; % ADW
metaData.links.id_Taxo = '172875'; % Taxonomicon
metaData.links.id_WoRMS = '1026595'; % WoRMS
metaData.links.id_fishbase = 'Danio-rerio'; % fishbase

%% References

%
bibkey = 'Augu2011'; type = 'Article'; bib = [ ...
  'doi = {10.1016/j.cbpa.2011.03.016}, ' ...
  'author = {Augustine S., and Gagnaire B., and Floriani B. M., and Adam-Guillermin C., and Kooijman S.A.L.M.}, ' ...
  'year  = {2011}, ' ...
  'title = {Developmental energetics of zebrafish, \emph{Danio rerio}}, ' ...
  'journal = {Comparative Biochemistry and Physiology, Part A}, ' ...
  'volume = {159}, ' ...
  'pages = {275-283}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];


%
bibkey = 'BagaPels2001'; type = 'Article'; bib = [ ...
  'author = {Bagatto, B. and Pelster, B. and Burggren, W. W.}, ' ...
  'year  = {2001}, ' ...
  'title = {Growth and metabolism of larval zebrafish: effects of swim training}, ' ...
  'journal = {Journal of Experimental Biology}, ' ...
  'volume = {204}, ' ...
  'pages = {4335-4343}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'BeauGous2015'; type = 'Article'; bib = [ ...
  'doi = {10.1371/journal.pone.0125841}, ' ...
  'author = {Beaudouin, R. and Goussen, B. and Piccini, B. and Augustine, S. and Devillers, J. and Brion, F. and P\`{e}ry, A. R. R.}, ' ...
  'year  = {2015}, ' ...
  'title = {An Individual-Based Model of Zebrafish Population Dynamics Accounting for Energy Dynamics}, ' ...
  'journal = {PloS one}, ' ...
  'volume = {10}, ' ...
  'number = {5}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'BestAdat2010'; type = 'Article'; bib = [ ...
  'author = {Best, J. and Adatto, I. and Cockington, J. and James, A. and Lawrence, C.}, ' ...
  'year  = {2010}, ' ...
  'title = {A novel method for rearing first feeding larval zebrafish: polyculture with {T}ype {L} saltwater rotifers (\emph{Brachionus plicatilis}).}, ' ...
  'journal = {Zebrafish}, ' ...
  'volume = {352 7(3)}, ' ...
  'pages = {89-295}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'EatoFarl1974a'; type = 'Article'; bib = [ ...
  'author = {Eaton, R. C. and Farley, R. D.}, ' ...
  'year  = {1974}, ' ...
  'title = {Growth and the reduction of depensation of zebrafish, \emph{Brachydanio rerio}, reared in the laboratory}, ' ...
  'journal = {Copeia}, ' ...
  'volume = {1}, ' ...
  'pages = {204-209}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'EatoFarl1974b'; type = 'Article'; bib = [ ...
  'author = {Eaton, R. C. and Farley, R. D.}, ' ...
  'year  = {1974}, ' ...
  'title = {Spawning cycle and egg production of zebrafish, \emph{Brachydanio rerio} in the laboratory}, ' ...
  'journal = {Copeia}, ' ...
  'volume = {1}, ' ...
  'pages = {195-204}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'ForbPres2010'; type = 'Article'; bib = [ ...
  'author = {Forbes, E. L. and Preston, C. D. and Lokman, P. M.}, ' ...
  'year  = {2010}, ' ...
  'title = {Zebrafish (\emph{Danio rerio}) and the egg size versus egg number trade off: effects of ration size on fecundity are not mediated by orthologues of the {F}ec gene}, ' ...
  'journal = {Reprod. Fert. Dev.}, ' ...
  'volume = {22}, ' ...
  'pages = {1015-1021}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'GerhKauf2002'; type = 'Article'; bib = [ ...
  'author = {Gerhard, G. S. and Kauffman, E. J. and Wang, X. and Stewart, R. and Moore, J. L. and Kasales, C. J. and Demidenko, E. and Cheng, K. C.}, ' ...
  'year  = {2002}, ' ...
  'title = {Life spans and senescent phenotypes in two strains of Zebrafish (\emph{Danio rerio})}, ' ...
  'journal = {Experimental Gerontology}, ' ...
  'volume = {37(8-9)}, ' ...
  'pages = {1055-1068}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'LawrEber2008'; type = 'Article'; bib = [ ...
  'author = {Lawrence, C. and Ebersole, J. P. and Kesseli, R. V.}, ' ...
  'year = {2008}, ' ...
  'title = {Rapid growth and out-crossing promote female development in zebrafish (\emph{Danio rerio})}, ' ...
  'journal = {Environ. Biol. Fish.}, ' ...
  'volume = {81}, '...
  'pages = {239-246}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'Schi2002'; type = 'Incollection'; bib = [ ...
  'author = {Schilling, T. F.}, ' ...
  'year  = {2002}, ' ...
  'booktitle = {Zebrafish: a practical guide}, ' ...
  'editor = {Nusslein-Volhard, C. and Dahm, R.}, ' ...
  'title = {The morphology of larval and adult zebrafish}, ' ...
  'publisher = {Oxford University Press Inc.}, ' ...
  'address = {New York}, ' ...
  'pages = {59-83}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'SpenGerl2008'; type = 'Article'; bib = [ ...
  'author = {Spence, R. and Gerlach, G. and Lawrence, C. and Smith, C.}, ' ...
  'year = {2008}, ' ...
  'title = {The behaviour and ecology of the zebrafish, \emph{Danio rerio}}, ' ...
  'journal = {Biol. Rev.}, ' ...
  'volume = {83}, '...
  'pages = {13-34}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'ValKwa2022'; type = 'Article'; bib = [ ...
  'author = {Valentine, S. and Kwasek, K.}, ' ...
  'year = {2022}, ' ...
  'title = {Feeding Rate and Protein Quality Differentially Affect Growth and Feeding Efficiency Response Variables of Zebrafish (Danio rerio)}, ' ...
  'journal = {Zebrafish}, ' ...
  'volume = {19 3}, ' ...
  'pages = {94-103}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

%
bibkey = 'YangYama2019'; type = 'Article'; bib = [ ...
  'author = {Yang, P. and Yamaki, M., Kuwabara, S., Kajiwara, R., Itoh, M.}, ' ...
  'year = {2019}, ' ...
  'title = {A newly developed feeder and oxygen measurement system reveals the effects of aging and obesity on the metabolic rate of zebrafish}, ' ...
  'journal = {Experimental Gerontology}, ' ...
  'volume = {129}, ' ...
  'pages = {110720}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
